### ISSUE TITLE
Laravel 9.2 Issue

### ISSUE THREAD

**Issue by andreladocruz** [spatie/laravel-google-cloud-storage#10]
Hi,

I'm using it in my Laravel 9 project with the following code:

![image](https://user-images.githubusercontent.com/3315596/155797153-e38e4eb2-0297-4eee-961c-d23630b22670.png)

the put method returns false and no file is created.

No exception thrown.

Any help?

**Comment by andreladocruz** [comment]
Found the issue. =P 

change "key_file" to "key_file_path" in filesystems.php

Sorry

**Comment by MatheusAparecido** [comment]
Hey @andreladocruz how are you?

I'm having the exact same issue. That's how I declared the configs on my filesystems.php.

![image](https://user-images.githubusercontent.com/50770574/156591733-ba4264b5-cb7d-46bc-8723-7c93a43f6c6b.png)

How did you fixed it?

**Comment by andreladocruz** [comment]
I think you must use only one key.

key_file_path or key_file. 

![image](https://user-images.githubusercontent.com/3315596/156602515-66d40c51-0f49-44ad-87bd-36299acc9d98.png)

**Comment by MatheusAparecido** [comment]
@andreladocruz Didn't work :(
Would it possible be a misconfiguration in my bucket?

When I try to debug my storage var, it keeps returning false.

![image](https://user-images.githubusercontent.com/50770574/156607083-85eddc88-f4e0-4dce-9dde-b15fba78a692.png)

![image](https://user-images.githubusercontent.com/50770574/156607171-27e189eb-c1a0-4856-b7e8-76f911aa16c9.png)

**Comment by andreladocruz** [comment]
I think $request->file is an object and has a method called "storePubliclyAs".

**Comment by ghike** [comment]
I'm working with @MatheusAparecido on the solution of this problem.

What we already tried:
- Using the JSON file provided by the GCS (authenticating through service_account).
- Using the key_file array, with all variables declared in the `.env` file.
- Using the StorePubliclyAs() and Store() methods.

Using both methods returned "false" as response when we're debugging the $disk->put('folder/', $image) method. But when we try to retrieve the file from the blobstorage, we receive it sucessfully.

@andreladocruz @AlexVanderbist any possible issues that could be causing this? :(

**Comment by andreladocruz** [comment]
Has the file is been written to GCS?

I really did not check the result of a successful write.

**Comment by ghike** [comment]
Well, after two days trying to solve this problem, we decided to port our project back to Laravel 8 (since we had the GCS implemented in other projects in this version).

**Comment by jacksontong** [comment]
for me the `put` method always return false while can I still make a directory `\Illuminate\Support\Facades\Storage::makeDirectory()`

**Comment by jacksontong** [comment]
I found that you can add `throw` to config so `put` will throw exception rather than return `false`

```
'gcs' => [
            'driver' => 'gcs',
            'throw' => true,
]
```

In my case the error is 
```
"message": "Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access"
```

**Comment by vladan-me** [comment]
> I found that you can add `throw` to config so `put` will throw exception rather than return `false`
> 
> ```
> 'gcs' => [
>             'driver' => 'gcs',
>             'throw' => true,
> ]
> ```
> 
> In my case the error is
> 
> ```
> "message": "Cannot insert legacy ACL for an object when uniform bucket-level access is enabled. Read more at https://cloud.google.com/storage/docs/uniform-bucket-level-access"
> ```

As a follow-up for the error, it's solved within the package itself, namely `filesystems.php` configuration

`'visibility_handler' => \League\Flysystem\GoogleCloudStorage\UniformBucketLevelAccessVisibility::class`
