### ISSUE TITLE
Unable to check existence in Laravel 9

### ISSUE THREAD

**Issue by umang200** [spatie/laravel-google-cloud-storage#14]
League\\Flysystem\\UnableToCheckFileExistence

"function": "forLocation",
            "class": "League\\Flysystem\\UnableToCheckExistence",
            "type": "::"

**Comment by freekmurze** [comment]
Too little info, feel free to send a PR that fixes the problem for you.

**Comment by umang200** [comment]
> Too little info, feel free to send a PR that fixes the problem for you.
![git](https://user-images.githubusercontent.com/87923717/158136405-5ad968c4-92d1-4c0a-8104-a9c1b60c3900.png)

**Comment by fitztrev** [comment]
I got this error too. I was able to resolve it by making sure:

1. Bucket is correct in config
2. Project ID is correct in config
3. Service account has sufficient permissions
