### ISSUE TITLE
File is not uploaded to bucket, read is possible

### ISSUE THREAD

**Issue by souljacker** [spatie/laravel-google-cloud-storage#30]
### Discussed in https://github.com/spatie/laravel-google-cloud-storage/discussions/29

<div type='discussions-op-text'>

<sup>Originally posted by **souljacker** June 24, 2022</sup>
I'm running Laravel 9, and just installed the package.

In my ENV I'm using these vars with the correct data
GOOGLE_CLOUD_STORAGE_BUCKET=
GOOGLE_CLOUD_KEY_FILE=
FILESYSTEM_DISK=gcs

I can confirm it works because I manually updated a jpeg to the bucket and this returns true:
`Storage::exists('teste.jpeg');`

If I try for any other filename it returns false, so it's actually reading the bucket.

Trying to write to the bucket, though, won't work nor return any errors.

This, does nothing:

`Storage::put('teste.txt',` 'asdasdadasddaasd');

I gave admin access to my service account, so I don't think it's permissions.

Any ideas?

</div>

**Comment by peterfox** [comment]
I'm also having this issue, my guess it it's a permissions issue somewhere and not the library, but it's frustrating

**Comment by souljacker** [comment]
> I'm also having this issue, my guess it it's a permissions issue somewhere and not the library, but it's frustrating

I wouldn't think so. I tried with an Owner of the project role and also as Storage Admin role.

Both have read access but won't write. The more frustrating is there's no error message at all

**Comment by souljacker** [comment]
Ok, solved it by changing 'visibility' to

'visibility' => PortableVisibilityHandler::NO_PREDEFINED_VISIBILITY,


in filesystems.php config file.

**Comment by peterfox** [comment]
Can confirm, fixed the problem for me.

**Comment by ansezz** [comment]
Thanks @souljacker

**Comment by TimoKoerber** [comment]
Thanks @souljacker for the solution 🥳 this was driving me crazy.

**Comment by makinita** [comment]
Thanks @souljacker it worked for me too...

**Comment by freekmurze** [comment]
Reading through this, I don't think we need to make any changes to the code.

Feel free to send a PR to the readme to make it more clear.
