### ISSUE TITLE
Filesystem

### ISSUE THREAD

**Issue by msalaoniric** [spatie/laravel-google-cloud-storage#4]
Is not using the filesystem config properly.... When we set the path_prefix, it's actually ignoring it. Also, when we set the storage_api_url, the bucket url is not correctly formed, as it takes the storage.googleapis.com URL from the images instead of the one we set.

```
'products' => [
            'driver'                => 'gcs',
            'key_file_path'         => storage_path('xxx_gae.json'),
            'project_id'            => 'xxxxxxxxxxx',
            'bucket'                => 'static.xxxxxxxxx.com',
            'path_prefix'           => 'dev/products',
            'storage_api_uri'       => 'https://static.xxxxxxxxx.com/',
            'visibility'            => 'public'
        ],
```

And to get the URL
`Storage::disk('products')->url($this->image)`

We are getting: 
`https://storage.googleapis.com/static.xxxxxxxxx.com/<img>`

Instead of:
`https://static.xxxxxxxxx.com/<path_prefix>/<img>`

**Comment by freekmurze** [comment]
Will be fixed in the next release.
