### ISSUE TITLE
copy and move methods don't work

### ISSUE THREAD

**Issue by ivictor777** [spatie/laravel-google-cloud-storage#76]
Hello! The copy and move methods don't work. There are no errors, the file is simply not copied or moved and the methods return false.

**Comment by freekmurze** [comment]
We'd welcome a PR for this that fixed it.

**Comment by grzegorz-bach** [comment]
I have the same issue but only if the permissions are set on bucket level (Uniform bucket level access). I've tried that dedicated visibility handler mentioned in [the readme](https://github.com/spatie/laravel-google-cloud-storage#uniform-bucket-level-access), but it didn't help.
