### ISSUE TITLE
Storage::disk('gcs')->url() Method broken in 2.2.4

### ISSUE THREAD

**Issue by andreladocruz** [spatie/laravel-google-cloud-storage#78]
Hi,

After updating to 2.2.4 we found an issue.

In version 2.2.3 calling the method Storage::disk('gcs')->url('test.txt') returned 

`https://storage.googleapis.com/disk.dev.clkdmg.site/test.txt`

In 2.2.4 it returns 

`/test.txt`

The storage_api_uri and the path_prefix are blank.

**Comment by freekmurze** [comment]
I'd accept a PR that fixes this.

**Comment by beschoenen** [comment]
@andreladocruz How is your `gcs` disk configured?

2.2.4 returns this for me:

```php
> Storage::disk('gcs')->url('test')
= "https://storage.googleapis.com/test"
```

With this config

```php
'gcs' => [
    'driver' => 'gcs',
    'key_file_path' => env('GOOGLE_CLOUD_KEY_FILE'),
    'key_file' => [],
    'project_id' => env('GOOGLE_CLOUD_PROJECT_ID'),
    'bucket' => env('GOOGLE_CLOUD_STORAGE_BUCKET'),
    'path_prefix' => env('GOOGLE_CLOUD_STORAGE_PATH_PREFIX', ''),
    'storage_api_uri' => env('GOOGLE_CLOUD_STORAGE_API_URI'),
    'api_endpoint' => env('GOOGLE_CLOUD_STORAGE_API_ENDPOINT'),
    'visibility' => 'public',
],
```

**Comment by andreladocruz** [comment]
@beschoenen ,

We don't have a default value to "GOOGLE_CLOUD_STORAGE_API_URI".

`'gcs' => [
            'driver' => 'gcs',
            'project_id' => env('GOOGLE_CLOUD_PROJECT_ID', 'dev-env-209015'),
            'key_file_path' => 'our_key_path',
            'bucket' => env('GOOGLE_CLOUD_STORAGE_BUCKET', 'our_deafult_bucket'),
            'path_prefix' => env('GOOGLE_CLOUD_STORAGE_PATH_PREFIX', ''),
            'visibility' => 'public',
            'storage_api_uri' => env('GOOGLE_CLOUD_STORAGE_API_URI', ''),
            'metadata' => ['cacheControl' => 'public,max-age=86400'],
        ],`

**Comment by beschoenen** [comment]
@andreladocruz You shouldn't give `GOOGLE_CLOUD_STORAGE_API_URI` a default value of `''`. 

I've fixed this in my PR.

**Comment by andreladocruz** [comment]
@beschoenen, why??

It was working before 2.2.4 version.

**Comment by beschoenen** [comment]
You're right that it should work, that's why I made the PR to fix it.
But I don't see anything in the readme.md about having `''` as a valid default value for that env. So it seems that it worked previously per coincidence

**Comment by andreladocruz** [comment]
@beschoenen , 

thanks =)

I got a little confused. =P

**Comment by andreladocruz** [comment]
Thanks =)
