### ISSUE TITLE
bucket not show on the url

### ISSUE THREAD

**Issue by MilesWuCode** [spatie/laravel-google-cloud-storage#88]
Laravel 11
laravel-google-cloud-storage 2.3.0

![image](https://github.com/spatie/laravel-google-cloud-storage/assets/1192835/212c5336-bb45-4332-89d2-b7566c9e41b9)

![image](https://github.com/spatie/laravel-google-cloud-storage/assets/1192835/2faf1358-8da7-4afd-a647-3216d2b626cf)

**Comment by luminagedev** [comment]
I have the same issue

**Comment by MilesWuCode** [comment]
> I have the same issue

GOOGLE_CLOUD_STORAGE_API_URI     set empty
