### ISSUE TITLE
metadata not updating after we upload to cloud storage

### ISSUE THREAD

**Issue by bairamispanagiotis** [spatie/laravel-google-cloud-storage#9]
Hello,

We recently used this library for our laravel app. We followed the documentation in order to configure it. We face an issue where, even though we are setting some metadata options, we don't see them implemented on GCS.

```
'cdn' => [
            'driver' => 'gcs',
            'project_id' => env('GOOGLE_CDN_PROJECT_ID', 'test'),
            'key_file_path' => base_path(env('GOOGLE_COM_CDN_SERVICE_JSON', 'test.json')), // optional: /path/to/service-account.json
            'bucket' => env('GOOGLE_CLOUD_STORAGE_BUCKET', 'test'),
            'path_prefix' => env('GOOGLE_CLOUD_STORAGE_PATH_PREFIX', ''), // optional: /default/path/to/apply/in/bucket
            'storage_api_uri' => env('GOOGLE_CLOUD_STORAGE_API_URI', ''), // see: Public URLs below
            'visibility' => 'public', // optional: public|private
            'metadata' => ['cacheControl' => 'no-cache,max-age:0']
        ]
```

![image](https://user-images.githubusercontent.com/3509439/154096741-9fc1c597-58e9-4982-8d7d-774e142019be.png)

**Comment by mmachatschek** [comment]
The library currently forwards all the options provided in the configuration to the underlying flysystem v3 library. There is an issue on the flysystem v3 repo that tries to solve this as its currently not supported to use the metadata configuration.

https://github.com/thephpleague/flysystem/pull/1299

**Comment by andreladocruz** [comment]
@bairamispanagiotis,

All files are created as private.

Even if our configuration shows as public.

This is the same issue?

**Comment by mmachatschek** [comment]
@andreladocruz this has something to do with your visibility settings when uploading the files. You can go to the storage block in Google Cloud Console and check if its set to private. If it is, you are not able to access the object with a normal url, otherwise you would either need to create a signed url to the object or fix the visibility setting.

**Comment by litan1106** [comment]
the metadata didn't work for me either.

'metadata' => ['cacheControl'=> 'public,max-age=86400', 'contentDisposition' => 'attachment'],

**Comment by mmachatschek** [comment]
With the release of flysystem v3.0.15, this issue should be fixed. Maybe it would be worth, bumping the minimum required version of ´league/flysystem-google-cloud-storage´ in the composer file.

**Comment by freekmurze** [comment]
Closing as it's fixed in flysystem 👍
